# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/aesophor/Code/Wmderland

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/aesophor/Code/Wmderland

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aesophor/Code/Wmderland/CMakeFiles /home/aesophor/Code/Wmderland/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aesophor/Code/Wmderland/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Wmderland

# Build rule for target.
Wmderland: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Wmderland
.PHONY : Wmderland

# fast build rule for target.
Wmderland/fast:
	$(MAKE) -f CMakeFiles/Wmderland.dir/build.make CMakeFiles/Wmderland.dir/build
.PHONY : Wmderland/fast

src/action.o: src/action.cpp.o

.PHONY : src/action.o

# target to build an object file
src/action.cpp.o:
	$(MAKE) -f CMakeFiles/Wmderland.dir/build.make CMakeFiles/Wmderland.dir/src/action.cpp.o
.PHONY : src/action.cpp.o

src/action.i: src/action.cpp.i

.PHONY : src/action.i

# target to preprocess a source file
src/action.cpp.i:
	$(MAKE) -f CMakeFiles/Wmderland.dir/build.make CMakeFiles/Wmderland.dir/src/action.cpp.i
.PHONY : src/action.cpp.i

src/action.s: src/action.cpp.s

.PHONY : src/action.s

# target to generate assembly for a file
src/action.cpp.s:
	$(MAKE) -f CMakeFiles/Wmderland.dir/build.make CMakeFiles/Wmderland.dir/src/action.cpp.s
.PHONY : src/action.cpp.s

src/client.o: src/client.cpp.o

.PHONY : src/client.o

# target to build an object file
src/client.cpp.o:
	$(MAKE) -f CMakeFiles/Wmderland.dir/build.make CMakeFiles/Wmderland.dir/src/client.cpp.o
.PHONY : src/client.cpp.o

src/client.i: src/client.cpp.i

.PHONY : src/client.i

# target to preprocess a source file
src/client.cpp.i:
	$(MAKE) -f CMakeFiles/Wmderland.dir/build.make CMakeFiles/Wmderland.dir/src/client.cpp.i
.PHONY : src/client.cpp.i

src/client.s: src/client.cpp.s

.PHONY : src/client.s

# target to generate assembly for a file
src/client.cpp.s:
	$(MAKE) -f CMakeFiles/Wmderland.dir/build.make CMakeFiles/Wmderland.dir/src/client.cpp.s
.PHONY : src/client.cpp.s

src/config.o: src/config.cpp.o

.PHONY : src/config.o

# target to build an object file
src/config.cpp.o:
	$(MAKE) -f CMakeFiles/Wmderland.dir/build.make CMakeFiles/Wmderland.dir/src/config.cpp.o
.PHONY : src/config.cpp.o

src/config.i: src/config.cpp.i

.PHONY : src/config.i

# target to preprocess a source file
src/config.cpp.i:
	$(MAKE) -f CMakeFiles/Wmderland.dir/build.make CMakeFiles/Wmderland.dir/src/config.cpp.i
.PHONY : src/config.cpp.i

src/config.s: src/config.cpp.s

.PHONY : src/config.s

# target to generate assembly for a file
src/config.cpp.s:
	$(MAKE) -f CMakeFiles/Wmderland.dir/build.make CMakeFiles/Wmderland.dir/src/config.cpp.s
.PHONY : src/config.cpp.s

src/cookie.o: src/cookie.cpp.o

.PHONY : src/cookie.o

# target to build an object file
src/cookie.cpp.o:
	$(MAKE) -f CMakeFiles/Wmderland.dir/build.make CMakeFiles/Wmderland.dir/src/cookie.cpp.o
.PHONY : src/cookie.cpp.o

src/cookie.i: src/cookie.cpp.i

.PHONY : src/cookie.i

# target to preprocess a source file
src/cookie.cpp.i:
	$(MAKE) -f CMakeFiles/Wmderland.dir/build.make CMakeFiles/Wmderland.dir/src/cookie.cpp.i
.PHONY : src/cookie.cpp.i

src/cookie.s: src/cookie.cpp.s

.PHONY : src/cookie.s

# target to generate assembly for a file
src/cookie.cpp.s:
	$(MAKE) -f CMakeFiles/Wmderland.dir/build.make CMakeFiles/Wmderland.dir/src/cookie.cpp.s
.PHONY : src/cookie.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/Wmderland.dir/build.make CMakeFiles/Wmderland.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/Wmderland.dir/build.make CMakeFiles/Wmderland.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/Wmderland.dir/build.make CMakeFiles/Wmderland.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/properties.o: src/properties.cpp.o

.PHONY : src/properties.o

# target to build an object file
src/properties.cpp.o:
	$(MAKE) -f CMakeFiles/Wmderland.dir/build.make CMakeFiles/Wmderland.dir/src/properties.cpp.o
.PHONY : src/properties.cpp.o

src/properties.i: src/properties.cpp.i

.PHONY : src/properties.i

# target to preprocess a source file
src/properties.cpp.i:
	$(MAKE) -f CMakeFiles/Wmderland.dir/build.make CMakeFiles/Wmderland.dir/src/properties.cpp.i
.PHONY : src/properties.cpp.i

src/properties.s: src/properties.cpp.s

.PHONY : src/properties.s

# target to generate assembly for a file
src/properties.cpp.s:
	$(MAKE) -f CMakeFiles/Wmderland.dir/build.make CMakeFiles/Wmderland.dir/src/properties.cpp.s
.PHONY : src/properties.cpp.s

src/tree.o: src/tree.cpp.o

.PHONY : src/tree.o

# target to build an object file
src/tree.cpp.o:
	$(MAKE) -f CMakeFiles/Wmderland.dir/build.make CMakeFiles/Wmderland.dir/src/tree.cpp.o
.PHONY : src/tree.cpp.o

src/tree.i: src/tree.cpp.i

.PHONY : src/tree.i

# target to preprocess a source file
src/tree.cpp.i:
	$(MAKE) -f CMakeFiles/Wmderland.dir/build.make CMakeFiles/Wmderland.dir/src/tree.cpp.i
.PHONY : src/tree.cpp.i

src/tree.s: src/tree.cpp.s

.PHONY : src/tree.s

# target to generate assembly for a file
src/tree.cpp.s:
	$(MAKE) -f CMakeFiles/Wmderland.dir/build.make CMakeFiles/Wmderland.dir/src/tree.cpp.s
.PHONY : src/tree.cpp.s

src/tree_node.o: src/tree_node.cpp.o

.PHONY : src/tree_node.o

# target to build an object file
src/tree_node.cpp.o:
	$(MAKE) -f CMakeFiles/Wmderland.dir/build.make CMakeFiles/Wmderland.dir/src/tree_node.cpp.o
.PHONY : src/tree_node.cpp.o

src/tree_node.i: src/tree_node.cpp.i

.PHONY : src/tree_node.i

# target to preprocess a source file
src/tree_node.cpp.i:
	$(MAKE) -f CMakeFiles/Wmderland.dir/build.make CMakeFiles/Wmderland.dir/src/tree_node.cpp.i
.PHONY : src/tree_node.cpp.i

src/tree_node.s: src/tree_node.cpp.s

.PHONY : src/tree_node.s

# target to generate assembly for a file
src/tree_node.cpp.s:
	$(MAKE) -f CMakeFiles/Wmderland.dir/build.make CMakeFiles/Wmderland.dir/src/tree_node.cpp.s
.PHONY : src/tree_node.cpp.s

src/util.o: src/util.cpp.o

.PHONY : src/util.o

# target to build an object file
src/util.cpp.o:
	$(MAKE) -f CMakeFiles/Wmderland.dir/build.make CMakeFiles/Wmderland.dir/src/util.cpp.o
.PHONY : src/util.cpp.o

src/util.i: src/util.cpp.i

.PHONY : src/util.i

# target to preprocess a source file
src/util.cpp.i:
	$(MAKE) -f CMakeFiles/Wmderland.dir/build.make CMakeFiles/Wmderland.dir/src/util.cpp.i
.PHONY : src/util.cpp.i

src/util.s: src/util.cpp.s

.PHONY : src/util.s

# target to generate assembly for a file
src/util.cpp.s:
	$(MAKE) -f CMakeFiles/Wmderland.dir/build.make CMakeFiles/Wmderland.dir/src/util.cpp.s
.PHONY : src/util.cpp.s

src/wm.o: src/wm.cpp.o

.PHONY : src/wm.o

# target to build an object file
src/wm.cpp.o:
	$(MAKE) -f CMakeFiles/Wmderland.dir/build.make CMakeFiles/Wmderland.dir/src/wm.cpp.o
.PHONY : src/wm.cpp.o

src/wm.i: src/wm.cpp.i

.PHONY : src/wm.i

# target to preprocess a source file
src/wm.cpp.i:
	$(MAKE) -f CMakeFiles/Wmderland.dir/build.make CMakeFiles/Wmderland.dir/src/wm.cpp.i
.PHONY : src/wm.cpp.i

src/wm.s: src/wm.cpp.s

.PHONY : src/wm.s

# target to generate assembly for a file
src/wm.cpp.s:
	$(MAKE) -f CMakeFiles/Wmderland.dir/build.make CMakeFiles/Wmderland.dir/src/wm.cpp.s
.PHONY : src/wm.cpp.s

src/workspace.o: src/workspace.cpp.o

.PHONY : src/workspace.o

# target to build an object file
src/workspace.cpp.o:
	$(MAKE) -f CMakeFiles/Wmderland.dir/build.make CMakeFiles/Wmderland.dir/src/workspace.cpp.o
.PHONY : src/workspace.cpp.o

src/workspace.i: src/workspace.cpp.i

.PHONY : src/workspace.i

# target to preprocess a source file
src/workspace.cpp.i:
	$(MAKE) -f CMakeFiles/Wmderland.dir/build.make CMakeFiles/Wmderland.dir/src/workspace.cpp.i
.PHONY : src/workspace.cpp.i

src/workspace.s: src/workspace.cpp.s

.PHONY : src/workspace.s

# target to generate assembly for a file
src/workspace.cpp.s:
	$(MAKE) -f CMakeFiles/Wmderland.dir/build.make CMakeFiles/Wmderland.dir/src/workspace.cpp.s
.PHONY : src/workspace.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... Wmderland"
	@echo "... edit_cache"
	@echo "... src/action.o"
	@echo "... src/action.i"
	@echo "... src/action.s"
	@echo "... src/client.o"
	@echo "... src/client.i"
	@echo "... src/client.s"
	@echo "... src/config.o"
	@echo "... src/config.i"
	@echo "... src/config.s"
	@echo "... src/cookie.o"
	@echo "... src/cookie.i"
	@echo "... src/cookie.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/properties.o"
	@echo "... src/properties.i"
	@echo "... src/properties.s"
	@echo "... src/tree.o"
	@echo "... src/tree.i"
	@echo "... src/tree.s"
	@echo "... src/tree_node.o"
	@echo "... src/tree_node.i"
	@echo "... src/tree_node.s"
	@echo "... src/util.o"
	@echo "... src/util.i"
	@echo "... src/util.s"
	@echo "... src/wm.o"
	@echo "... src/wm.i"
	@echo "... src/wm.s"
	@echo "... src/workspace.o"
	@echo "... src/workspace.i"
	@echo "... src/workspace.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

